version: "3.1"
services:

  mailhog:
    image: mailhog/mailhog:latest
    container_name: laravel8login-mailhog
    ports:
      - "4001:8025"

  redis:
    image: redis:alpine
    container_name: laravel8login-redis

  mysql:
    image: mysql:8.0
    container_name: laravel8login-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    working_dir: /application
    volumes:
      - .:/application
    environment:
      - MYSQL_ROOT_PASSWORD=rootpasswordhere
      - MYSQL_DATABASE=logindb
      - MYSQL_USER=app
      - MYSQL_PASSWORD=app
    ports:
      - "3306:3306"

  webserver:
    image: nginx:alpine
    container_name: laravel8login-webserver
    working_dir: /application
    volumes:
      - .:/application
      - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "4000:80"

  php-fpm:
    build: ./phpdocker/php-fpm
    ports:
      - "8000:8000"
    container_name: laravel8login-php-fpm
    working_dir: /application
    volumes:
      - ./:/application
      - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini


  # docker exec -it laravel8login-php-fpm bash
  #find /application/ -type f -exec chmod 644 {} \;
  #find /application -type d -exec chmod 755 {} \;
  #chown -R 1000:1000 /application/
  #chmod -R 777 /application/storage
  #chmod -R 777 /application/bootstrap/cache/
  #chmod -R 777 /application/public/
  #php artisan serve --host 0.0.0.0
  #docker-compose exec php-fpm php artisan serve
  #docker-compose exec php-fpm php artisan serve


